name: Deploy (only tests for now)

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.14.1

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

  deploy-dev:
    needs: test
    runs-on: [self-hosted, cms-data-api]

    strategy:
      matrix:
        node-version: [18.16.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --legacy-peer-deps
    - run: pm2 restart cms-data-api

  deploy-prod:
    needs: test
    runs-on: [self-hosted, cms-data-api-host]

    strategy:
      matrix:
        node-version: [18.16.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --legacy-peer-deps
      env: 
        NODE_ENV: production
        SECRET_ACCESS_TOKEN: ${{ secrets.SECRET_ACCESS_TOKEN }}
        SECRET_REFRESH_TOKEN: ${{ secrets.SECRET_REFRESH_TOKEN }}
        SECRET_ACCESS_TIME: ${{ secrets.SECRET_ACCESS_TIME }}
        SECRET_REFRESH_TIME: ${{ secrets.SECRET_REFRESH_TIME }}
    - run: pm2 restart cms-data-api-host
